description: Deploy using the Freckle Platform CLI
inputs:
  platform-setup-version:
    description: Version of Platform CLI to install
    required: true
    default: ""
  platform-setup-token:
    description: GitHub token with access to freckle/platform artifacts
    required: true
  app-directory:
    description: Directory containing the App's .platform
    required: true
    default: "."
  app-resource:
    description: --resource option
    required: true
    default: ""
  environment:
    description: Environment to deploy (required)
    required: true
  slack-webhook:
    description: Slack Webhook URL, will not notify if empty
    required: true
    default: ""
outputs: {}
runs:
  using: composite
  steps:
    - uses: freckle/setup-platform-action@v6
      with:
        version: ${{ inputs.platform-setup-version }}
        token: ${{ inputs.platform-setup-token }}

    - shell: bash
      run: |
        cd '${{ inputs.app-directory }}'
        options=()

        if [[ -n '${{ inputs.app-resource }}' ]]; then
          options+=( --resource '${{ inputs.app-resource }}' )
        fi

        if platform --color always version &>/dev/null; then
          options+=( --color always )
        fi

        platform --environment '${{ inputs.environment }}' "${options[@]}" \
          deploy --tag '${{ github.sha }}' --no-confirm

    - if: ${{ always() && inputs.slack-webhook }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/freckle-automation.png?size=48
        SLACK_USERNAME: GitHub Actions
        SLACK_TITLE: ${{ github.repository }} deployment
        SLACK_MESSAGE: ${{ job.status }}
        SLACK_FOOTER: ''
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        MSG_MINIMAL: actions url,commit
