name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: ./
        with:
          dry-run: true
